insert into MOVIE ( name, experiences, listing_type) values ('Kabali', 'RDX, Dolby Atmos, SUB', 'NOW_SHOWING');
insert into MOVIE ( name, experiences, listing_type) values ('Sultan', 'RDX, Dolby Atmos, SUB', 'NOW_SHOWING');
insert into MOVIE ( name, experiences, listing_type) values ('Thirunaal', 'RDX', 'NOW_SHOWING');
insert into MOVIE ( name, experiences, listing_type) values ('Banjo', 'RDX 3D', 'NOW_SHOWING');
insert into MOVIE ( name, experiences, listing_type) values ('Suicide Squad', 'Dolby Atmos, RDX 3D, SUB', 'NOW_SHOWING');
insert into MOVIE ( name, experiences, listing_type) values ('Namadhu', 'RDX, SUB', 'NOW_SHOWING');
insert into MOVIE ( name, experiences, listing_type) values ('Pelli Chupulu', 'RDX, SUB', 'NOW_SHOWING');
insert into MOVIE ( name, experiences, listing_type) values ('Aandavan Kattalai', 'RDX, SUB', 'NOW_SHOWING');
insert into MOVIE ( name, experiences, listing_type) values ('Pink', 'RDX, SUB', 'NOW_SHOWING');
insert into MOVIE ( name, experiences, listing_type) values ('Remo', 'Dolby Atmos, RDX, SUB', 'NOW_SHOWING');
insert into MOVIE ( name, experiences, listing_type) values ('Inferno', 'Dolby Atmos, RDX, SUB', 'NOW_SHOWING');
insert into MOVIE ( name, experiences, listing_type) values ('The Accountant', 'RDX, SUB', 'NOW_SHOWING');